fos_user:
    db_driver: orm
    firewall_name: main
    service:
        mailer: fos_user.mailer.twig_swift
    user_class: App\Entity\User
    from_email:
        address:        noreply@website46.fr
        sender_name:    Morgane & David
