#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /resetting
